application:
  name: Cross Game MatchMaking | Ambiente HML

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cross_game?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
  data:
    rest:
      base-path: /api/hml